$DIR = $PSScriptRoot
$KOMOREBI_PATH = "$DIR/komorebi"
$WHKD_PATH = "$DIR"
$YASB_PATH = "$DIR/yasb"

SETX KOMOREBI_CONFIG_HOME $KOMOREBI_PATH
SETX WHKD_CONFIG_HOME $WHKD_PATH
SETX YASB_CONFIG_HOME $YASB_PATH

Write-Host "KOMOREBI_CONFIG_HOME set to $KOMOREBI_PATH"
Write-Host "WHKD_CONFIG_HOME set to $WHKD_PATH"
Write-Host "YASB_CONFIG_HOME set to $YASB_PATH"